spring:
  jackson:
    time-zone: ${APP_TIME_ZONE:America/Chicago}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlserver://localhost:1433;databaseName=transactionsdb;encrypt=true;trustServerCertificate=true}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:StrongPass123!}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
        jdbc:
          time_zone: ${APP_TIME_ZONE:America/Chicago}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring.json.add.type.headers: true
    consumer:
      group-id: transaction-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: com.geraldobuseh.transactionservice.kafka.event
    listener:
      missing-topics-fatal: false

jwt:
  secret: ${JWT_SECRET:your-super-secure-development-secret-key-change-this}
  expiration: ${JWT_EXPIRATION:3600000}

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} level=%5p correlationId=%X{correlationId:-none} username=%X{username:-anonymous} thread=%t logger=%logger{36} message=%m%n"
